const SUCCESS_STATUS = 200;
const NEW_RESOURCE_CREATED_STATUS = 201;

const BAD_REQUEST_STATUS = 400;
const UNAUTHORIZED_STATUS = 401;

const NOT_FOUND_STATUS = 404;

const INTERNAL_SERVER_ERROR = 500;

module.exports = {
    SUCCESS_STATUS,
    NEW_RESOURCE_CREATED_STATUS,
    BAD_REQUEST_STATUS,
    UNAUTHORIZED_STATUS,
    NOT_FOUND_STATUS,
    INTERNAL_SERVER_ERROR
};
